global:
    slack_api_url: 'https://hooks.slack.com/services/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'

  route:
    receiver: 'slack-notifications'

  receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#viktor_petrushenko'
