version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:latest
    ports:
      - ${PORT_IN}:${PORT_OUT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:latest
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:latest
    networks:
      - front_net
      - back_net

volumes:
    post_db:
networks:
    front_net:
      external: true
    back_net:
      external: true
