version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    image: ${USERNAME}/ui:2.0
    ports:
      - ${PORT_IN}:${PORT_OUT}/tcp
    networks:
      - front_net
  post:
    image: ${USERNAME}/post:1.0
    networks:
      - back_net
      - front_net
  comment:
    image: ${USERNAME}/comment:1.0
    networks:
      - front_net
      - back_net
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net
volumes:
    post_db:
    prometheus_data:

networks:
    front_net:
      external: true
    back_net:
      external: true
