version: '3.3'
services:
  zipkin:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - front_net
      - back_net

  fluentd:
    image: ${USERNAME}/fluentd
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.7.1
    expose:
      - 9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.7.1
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "5601:5601"

networks:
  back_net:
  front_net:
