version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:latest
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - 9292:${PORT}/tcp
    networks:
      - front_net
    depends_on:
      - post

      - ${PORT_IN}:${PORT_OUT}/tcp
    depends_on:
      - post
    networks:
      - front_net

    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui


  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post


  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comment

  post:
    image: ${USER_NAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net
  comment:
    image: ${USERNAME}/comment:latest

    networks:
      - front_net
      - back_net
volumes:
  post_db:
  prometheus_data:
networks:
  front_net:
  back_net:
