version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:2.0
    ports:
      - ${PORT_IN}:${PORT_OUT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - front_net
      - back_net
volumes:
    post_db:

networks:
    front_net:
      external: true
    back_net:
      external: true
